rules_folder: /opt/elastalert/rules
run_every:
  seconds: 30
buffer_time:
  minutes: 15
es_host: opensearch-node1
es_port: 9200
writeback_index: elastalert2_status
alert_time_limit:
  days: 2
use_ssl: true
verify_certs: true
ca_certs: /etc/elastalert/root-ca.pem
client_cert: /etc/elastalert/opensearch-admin.pem
client_key: /etc/elastalert/opensearch-admin-key.pem
notify_email: []
